version: '3'

services:
  mongo:
    image: mongo

  backend:
    build: backend
    ports:
      - "5000:5000"
    labels:
      - "traefik.frontend.rule=Host:backend.docker.localhost"
    depends_on: 
      - mongo
    environment: 
      - DB_URL=mongodb://mongo/become-a-legend
    restart: always

  frontend:
    build: frontend
    labels:
      - "traefik.frontend.rule=Host:frontend.docker.localhost"
    ports:
      - "8080:8080"
    depends_on: 
      - backend
    environment: 
      - VIRTUAL_HOST=app.becomealegend.com


  proxy:
    image: traefik
    command: --docker # Tells Traefik to listen to docker
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # So that Traefik can listen to the Docker events
